### ISSUE TITLE
Add apk

### ISSUE THREAD

**Issue by architjn** [klinker41/android-slidingactivity#1]
You should add an apk for testing so that we can try if we can use it somewhere or not.
By the way great work

**Comment by klinker41** [comment]
Sure, http://build.klinker.xyz/job/Andorid-SlidingActivity/lastSuccessfulBuild/artifact/sample/build/outputs/apk/sample-debug.apk

**Comment by klinker41** [comment]
Probably better to use this link actually: https://www.dropbox.com/s/zpr0ykwl07539uq/sliding-activity-sample.apk?dl=0
