### ISSUE TITLE
problem with google play service

### ISSUE THREAD

**Issue by masoudfcr** [klinker41/android-slidingactivity#16]
It has problem with google play service
when I add google play service in gradle and run the project it makes this runtime error:

            Could not find class 'android.support.v7.internal.view.menu.MenuBuilder', referenced from method android.support.v7.app.AppCompatDelegateImplV7.initializePanelMenu
            Could not find class 'android.support.v7.internal.view.menu.MenuBuilder', referenced from method android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu
            Could not find class 'android.support.v7.internal.view.menu.MenuBuilder', referenced from method android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel

why is that?

**Comment by klinker24** [comment]
I have never been able to reproduce this, but `v1.4.4` of the library updates to the latest support libraries and all of the SDK 25 tooling, so this should be fixed, if not, then the issue wouldn't be on our end
