### ISSUE TITLE
Do you have example with RecyclerView ? click to sliding activity

### ISSUE THREAD

**Issue by helmifluida** [klinker41/android-slidingactivity#17]

**Comment by willu2** [comment]
You can use with RecycleView. Do not create ScrolView and View in your recycler, and item. Create listener in ViewHolder, like `public class View_Holder extends RecyclerView.ViewHolder implements View.OnClickListener {....`
 ```
@Override
        public void onClick(View v) {
               Intent intent = new Intent(v.getContext(), FabActivity.class);
               v.getContext().startActivity(intent);
    }
```
after, if you clicked on item, activity (create).
