### ISSUE TITLE
Recycler view is not scrolling inside the Sliding Activity

### ISSUE THREAD

**Issue by koleshop** [klinker41/android-slidingactivity#23]
I have added a fragment inside my SlidingActivity. Inside the fragment, there is a RecyclerView.
Now the recycler view is not scrolling inside the sliding activity but if I add this fragment to an AppCompatActivity, then the scrolling is working fine.

**Comment by jiangecho** [comment]
I think the cause is ```  public boolean onInterceptTouchEvent(MotionEvent event) ``` in class ```MultiShrinkScroller```, you can just comment this method to do some test.

**Comment by iammert** [comment]
Same here. It does not scroll. Anyone find any solution yet?

**Comment by ClarkXP** [comment]
+1

**Comment by SreenuGGK** [comment]
+1

**Comment by klinker24** [comment]
If you set your `RecyclerView` height to `wrap_content`, it should work just fine: https://github.com/klinker41/android-slidingactivity/issues/7
