### ISSUE TITLE
Set image from URL?

### ISSUE THREAD

**Issue by willu2** [klinker41/android-slidingactivity#25]
How to set hader image from url?

**Comment by klinker41** [comment]
You'll need to download the image and then apply it manually.

Something like this would work if you are using Glide:

```java
Glide.with(this)
                .load(backdropUrl)
                .asBitmap()
                .into(ew SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
                        setImage(resource);
                    }
                });
```

I won't include an image loading library with this library though, that will be up to you to pick which works best for you and implement it.

**Comment by willu2** [comment]
Thanks for help.
