### ISSUE TITLE
How to slide to bottom programmatically?

### ISSUE THREAD

**Issue by Matt237** [klinker41/android-slidingactivity#27]
It's possible to set auto scroll to bottom programmatically?

**Comment by klinker41** [comment]
Not sure what you're asking. Do you want to close the activity by scrolling it off the bottom, or scroll the content to the bottom of the list? Just use `activity.finish()` and that should scroll it off the bottom of the screen.

**Comment by Matt237** [comment]
no,
the slide activity is like "scrollView".
I meant to scroll to the bottom of the activity without closing the actvity.
E.g ..lets say i have large content off text and the user needs to scroll
it down.. so, i want the activity opening on the bottom without making the
user to scroll it by himself. (like in ListView smoothScrollToPosition or
something like that).

**Comment by klinker41** [comment]
This is exactly the same as you would have in a normal activity, there are no differences. Just use your list view reference you have stored and smooth scroll to bottom the same as you always would.

**Comment by Matt237** [comment]
This is not what i meant.
But I have not used a ListView, just a simple TextView with a long content.

**Comment by klinker41** [comment]
Still the same answer. You could wrap the content in your own scrollview or the layout includes one with the id `content_scroller`.

**Comment by Matt237** [comment]
Ok thank's
