### ISSUE TITLE
Disable scroll on WebView

### ISSUE THREAD

**Issue by darin-lao** [klinker41/android-slidingactivity#3]
Can't not scroll content on WebView

    public void init(Bundle bundle) {
        disableHeader();
        setPrimaryColors(getResources().getColor(R.color.app_theme), getResources().getColor(R.color.app_theme));
        mWebView = new WebView(this);
        WebSettings settings = mWebView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setUseWideViewPort(true);
        settings.setSupportZoom(false);
        settings.setCacheMode(WebSettings.LOAD_NO_CACHE);
        settings.setBuiltInZoomControls(false);
        settings.setDomStorageEnabled(true);
        settings.setLoadWithOverviewMode(true);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB && Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
            mWebView.setLayerType(WebView.LAYER_TYPE_SOFTWARE, null);
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            mWebView.getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.TEXT_AUTOSIZING);
        } else {
            mWebView.getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NORMAL);
        }
        mWebView.setVerticalScrollBarEnabled(true);
                mWebView.loadUrl("http://weixin.qq.com/agreement?lang=zh_CN");

        setContent(mWebView);
    }

**Comment by klinker41** [comment]
This is working correctly for me when testing it on Nexus 6 running Android 6.0. Web content can be scrolled up and down and when you get to the top, you can pull the activity down to close it.

My guess is that the webview on your device is not correctly handling the touch intercept, but that isn't something I can fix in this library.

Note: I also added ```mWebView.setWebViewClient(new WebViewClient());``` in the init method, that could make a difference.

**Comment by darin-lao** [comment]
thank for your suggest,I found this issue on Moto X 5.1 and I have been resolve by ScrollView .

        ScrollView scroll=new ScrollView(this);
        mWebView.setVerticalScrollBarEnabled(true);
        mWebView.loadUrl("http://doc.zhangzhebang.com/app_agreement.html");
        scroll.addView(mWebView);
        setContent(scroll);
