### ISSUE TITLE
SlidingActivity is crashing after to upgrade android support libraries to 24.2.0 version

### ISSUE THREAD

**Issue by ClarkXP** [klinker41/android-slidingactivity#35]
`android.view.InflateException: Binary XML file line #56: Binary XML file line #56: Error inflating class android.support.design.widget.FloatingActionButton`
com.klinker.android.sliding.SlidingActivity.onCreate(SlidingActivity.java:107)

**Comment by klinker24** [comment]
I have never been able to reproduce this, but I have updated the library to `v1.4.4` that runs on the latest design support library and all of SDK 25's tooling. So this should be fixed.
