### ISSUE TITLE
How to add fab at bottom of the screen in Sliding Activity like a fab in cordinator layout?

### ISSUE THREAD

**Issue by avi2108** [klinker41/android-slidingactivity#36]
@klinker41  please help me .
I tried using cordinator layout as the sliding Activity content and kept FAB in that cordinator layout.
But as activity scrolls, fab also scrolling up and down.

**Comment by klinker24** [comment]
Yes this would happen. You would have to add the FAB dynamically to the `android.R.id.content` layout. 

This library is a good example of how that works: https://github.com/klinker41/Android-ActionButton

Dynamically create the object and add it to the top level activity `ViewGroup`
