### ISSUE TITLE
full screen tablet

### ISSUE THREAD

**Issue by oussamajebali** [klinker41/android-slidingactivity#37]
![screenshot_2016-10-25-17-06-16](https://cloud.githubusercontent.com/assets/5850650/19694242/cc3ac284-9ade-11e6-9110-8fe9fcbac3d0.png)

this is what i got in my tablet

How to fix that to get full screen please

**Comment by klinker41** [comment]
This is the expected behavior.

**Comment by oussamajebali** [comment]
@klinker41 thanks
i will try
