### ISSUE TITLE
didn't slide when using list view with items in a fab activity

### ISSUE THREAD

**Issue by emdessam** [klinker41/android-slidingactivity#40]
in an fab activity if i have text view with in paragraph it's slide but when i but when i using list view and 
items didn't slide

**Comment by klinker24** [comment]
Can you please give more description? We use this in various RecyclerViews and ListViews and has always worked. What happen when you try?

**Comment by emdessam** [comment]
in fab activity i put in content activity only list view tag.
i only replaced  textview tag with listview tag

**Comment by klinker24** [comment]
Are you talking about the layout within the sliding activity? If so, you need to use a RecyclerView with a static height instead of a ListView. 

Please see: https://github.com/klinker41/android-slidingactivity/issues/7

**Comment by emdessam** [comment]
Thank u at all when i switch to recyclerview is done
