### ISSUE TITLE
Close activity on sliding to bottom

### ISSUE THREAD

**Issue by AkshayChordiya** [klinker41/android-slidingactivity#41]
Currently when we slide the `SlidingActivity` to up it closes. Can we do the same on sliding down?
Similar to one in Inbox app.

**Comment by klinker41** [comment]
I would say sliding down is implemented and sliding up is not, but I guess you can call either what you wish. Not something I'll implement, but please feel free to do it and send me a PR.

**Comment by AkshayChordiya** [comment]
@klinker41 Sure I'll try it and if possible send you a PR

**Comment by klinker24** [comment]
We created a slightly different/modern variation of this library, that includes this functionality. If you are still interested, you can check it out here: https://github.com/klinker24/Android-DragDismissActivity
