### ISSUE TITLE
How to change title color manipulate with imageView of slider?

### ISSUE THREAD

**Issue by gigantz** [klinker41/android-slidingactivity#43]
How to change title color manipulate with imageView of slider?

`
    <style name="Theme.MyGreenTheme" parent="Theme.Sliding.Light">
        <item name="android:titleTextColor">@color/colorAccent</item>
    </style>
`

Thank you for the greatest lib I ever see. Just have this question

**Comment by klinker41** [comment]
The title's color is always defined as white (https://github.com/klinker41/android-slidingactivity/blob/master/library/src/main/res/layout/sliding_title.xml), it cannot be changed in your theme.

You could do something programmatically:

```java
TextView title = (TextView) findViewById(R.id.large_title);
title.setTextColor(getResources().getColor(R.color.colorAccent));
```
