### ISSUE TITLE
Coordinator layout appbar scroll behavior not working in sliding activity

### ISSUE THREAD

**Issue by apgapg** [klinker41/android-slidingactivity#45]
i have a recycler view below the appbar layout. The same is working in appCompatactivity but not in sliding activity. The recycler view isnt scrolling. i have also set recycler view to wrap_content

**Comment by klinker24** [comment]
This library isn't going to work with RecyclerView, it is for statically sized content. We have created a bit different variation of this library though, that will work with lists: https://github.com/klinker24/Android-DragDismissActivity
