### ISSUE TITLE
Translucent header, how disable?

### ISSUE THREAD

**Issue by objaa** [klinker41/android-slidingactivity#5]
Hello! Thanks you, for your awesome work!
I use your library and i have transperent header (+fab) :(

![2015-08-31 03-19-32](https://cloud.githubusercontent.com/assets/7000585/9570288/bbbf0ea6-4f8f-11e5-9b5b-2fb317cb5f42.PNG)

How i can remove transparency from header? 

My Activity have only 3 lines:
        setTitle(app.getTitle());
        setPrimaryColors(R.color.primary, R.color.primary_dark);
        setContent(R.layout.activity_detail);

R.color.primary - not transperent :o

**Comment by klinker41** [comment]
I'm not really sure what you're asking for...

**Comment by objaa** [comment]
I update screenshot in the first post. I have header with 50% opacity. Can i set opacity to 100%?
I want have that:
![2015-08-31 03-30-34](https://cloud.githubusercontent.com/assets/7000585/9570334/4c07509e-4f91-11e5-9969-631564303c78.PNG)

**Comment by klinker41** [comment]
You should probably just hide the header altogether if you don't want it to
have a background, it will look extremely awkward without color there and
it will accomplish your request to scroll the header with the rest of the
content without shrinking it.
