### ISSUE TITLE
Any way to minimise and activity than destroy it by swiping down?

### ISSUE THREAD

**Issue by jacob-abe** [klinker41/android-slidingactivity#57]
Is there any way to utilise this library or extend it to only minimise an activity on swipe down and keep as a snackbar when swiped down? I'm talking about similar functionality to youtube app where if you swipe down while watching a video, you can view other video lists while the currently playing video is minimised but not stopped.

**Comment by klinker24** [comment]
Sorry, no. That just isn't what this library is or is for.
