### ISSUE TITLE
Image header size

### ISSUE THREAD

**Issue by wrustel** [klinker41/android-slidingactivity#6]
Hi, nice library. I wanted to customize my image header size. How can I do that?

**Comment by klinker41** [comment]
This is not something that is currently supported and is not planned, it
messes up too many other parameters when trying to change it dynamically.
You'll have to change it manually in the library if you want this
functionality.

**Comment by wrustel** [comment]
Ok, I will try do dynamically in java code. If I do that I could give to you the code for a new custom relase.

Thank you
