### ISSUE TITLE
Listview does not scroll

### ISSUE THREAD

**Issue by mufaddalgulshan** [klinker41/android-slidingactivity#7]
Hi, i used your library and added a listview as the root element of the activity. However the listview would not scroll. Please can you help?

**Comment by klinker41** [comment]
I'm not surprised, this is more for fixed height items. Set the height of
the listview and it should work.

**Comment by mufaddalgulshan** [comment]
OK. Thanks, I'll try doing that.

**Comment by kaveeshkanwal** [comment]
Hi, i did try and fix the height of my list view. It's still not scrolling. Is there any other possible way of doing it? Thanks.

**Comment by Fenomen83** [comment]
Hi, i used your library and added a listview as the root element of the activity. However the listview would not scroll. Please can you help?

**Comment by kaveeshkanwal** [comment]
@Fenomen83 i just used a listview in an activity and gave that activity in and out animation. It is super easy!

**Comment by klinker24** [comment]
With the latest support libraries, `RecyclerView` can `wrap_content`. I would recommend using this for this implementation.

http://stackoverflow.com/a/35623177
